-- =====================================================================
-- 02_common_code.sql — 공통코드(TB_META_CODE) 초기 적재
-- 실행 순서: 2 / 3
-- 선행: 01_meta_ddl.sql
-- 후행: 03_initial_load.sql
-- 출처: DB_메타정보_관리체계_표준설계.md §5 / §5.1
-- 주의: CD_SERVICE는 사내 서비스 코드 체계에 맞게 별도 적재 필요
-- =====================================================================

-- CD_RETENTION_PERIOD
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_RETENTION_PERIOD','Y1','1년','1년',1,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_RETENTION_PERIOD','Y3','3년','3년',2,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_RETENTION_PERIOD','Y5','5년','5년',3,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_RETENTION_PERIOD','Y10','10년','10년',4,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_RETENTION_PERIOD','Y30','30년','30년',5,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_RETENTION_PERIOD','PERM','영구','영구',6,'INITIAL_LOAD','INITIAL_LOAD');

-- CD_PCI_CATEGORY (신용정보법 시행령 분류)
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_PCI_CATEGORY','IDENT','식별정보','식별정보 (신용정보법 시행령 분류)',1,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_PCI_CATEGORY','TRX','신용거래','신용거래 (신용정보법 시행령 분류)',2,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_PCI_CATEGORY','SCORE','신용도','신용도 (신용정보법 시행령 분류)',3,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_PCI_CATEGORY','ABILITY','신용능력','신용능력 (신용정보법 시행령 분류)',4,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_PCI_CATEGORY','PUBLIC','공공정보','공공정보 (신용정보법 시행령 분류)',5,'INITIAL_LOAD','INITIAL_LOAD');

-- CD_ISOLATION_LEVEL
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_ISOLATION_LEVEL','L1','운영망','운영망',1,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_ISOLATION_LEVEL','L2','준격리','준격리',2,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_ISOLATION_LEVEL','L3','완전격리','완전격리',3,'INITIAL_LOAD','INITIAL_LOAD');

-- CD_STATUS
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_STATUS','PLANNED','계획','계획',1,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_STATUS','ACTIVE','운영중','운영중',2,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_STATUS','DEPRECATED','폐기예정','폐기예정',3,'INITIAL_LOAD','INITIAL_LOAD');

-- CD_TABLE_TYPE
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_TABLE_TYPE','BASE','테이블','테이블',1,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_TABLE_TYPE','VIEW','뷰','뷰',2,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_TABLE_TYPE','MVIEW','MView','MView',3,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_TABLE_TYPE','EXT','외부','외부',4,'INITIAL_LOAD','INITIAL_LOAD');

-- CD_INDEX_TYPE
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_INDEX_TYPE','NORMAL','NORMAL','일반 인덱스',1,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_INDEX_TYPE','UNIQUE','UNIQUE','고유 인덱스',2,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_INDEX_TYPE','BITMAP','BITMAP','비트맵 인덱스',3,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_INDEX_TYPE','FUNCTION','FUNCTION','함수기반 인덱스',4,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_INDEX_TYPE','REVERSE','REVERSE','리버스키 인덱스',5,'INITIAL_LOAD','INITIAL_LOAD');

-- CD_INDEX_PURPOSE
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_INDEX_PURPOSE','PK','PK','기본키',1,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_INDEX_PURPOSE','FK','FK','외래키',2,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_INDEX_PURPOSE','SEARCH','SEARCH','조회',3,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_INDEX_PURPOSE','JOIN','JOIN','조인',4,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_INDEX_PURPOSE','TUNING','TUNING','튜닝',5,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_INDEX_PURPOSE','SORT','SORT','정렬',6,'INITIAL_LOAD','INITIAL_LOAD');

-- CD_SEQUENCE_PURPOSE
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_SEQUENCE_PURPOSE','PK','PK','기본키 채번',1,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_SEQUENCE_PURPOSE','BIZ_KEY','BIZ_KEY','업무키 채번',2,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_SEQUENCE_PURPOSE','TEMP','TEMP','임시 채번',3,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_SEQUENCE_PURPOSE','ETC','ETC','기타',4,'INITIAL_LOAD','INITIAL_LOAD');

-- CD_MASKING_RULE
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_MASKING_RULE','NAME','이름','이름',1,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_MASKING_RULE','RRN','주민번호','주민번호',2,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_MASKING_RULE','PHONE','전화번호','전화번호',3,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_MASKING_RULE','CARD','카드번호','카드번호',4,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_MASKING_RULE','EMAIL','이메일','이메일',5,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_MASKING_RULE','ADDR','주소','주소',6,'INITIAL_LOAD','INITIAL_LOAD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('CD_MASKING_RULE','FULL','전체마스킹','전체마스킹',7,'INITIAL_LOAD','INITIAL_LOAD');

-- CD_SERVICE: 사내 서비스 코드 체계에 맞게 별도 적재 (TODO)

COMMIT;
