-- =====================================================================
-- 02_common_code.sql — 공통코드(TB_META_CODE) 초기 적재
-- 실행 순서: 2 / 3
-- 선행: 01_meta_ddl.sql
-- 후행: 03_initial_load.sql
-- 출처: DB_메타정보_관리체계_표준설계.md §6.9
-- 주의: CD_SERVICE는 UNASSIGNED 더미 1건만 적재하며 실제 서비스 코드는 별도 적재
-- 재실행 안전성: 모든 코드 INSERT는 NOT EXISTS 가드, HIST INSERT는
--                ('I','INITIAL_LOAD') 중복 가드로 누적/충돌을 방지한다.
-- =====================================================================

-- CD_RETENTION_PERIOD
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_RETENTION_PERIOD','Y1','1년','1년',1,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_RETENTION_PERIOD' AND CODE_VALUE='Y1');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_RETENTION_PERIOD','Y3','3년','3년',2,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_RETENTION_PERIOD' AND CODE_VALUE='Y3');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_RETENTION_PERIOD','Y5','5년','5년',3,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_RETENTION_PERIOD' AND CODE_VALUE='Y5');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_RETENTION_PERIOD','Y10','10년','10년',4,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_RETENTION_PERIOD' AND CODE_VALUE='Y10');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_RETENTION_PERIOD','Y30','30년','30년',5,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_RETENTION_PERIOD' AND CODE_VALUE='Y30');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_RETENTION_PERIOD','PERM','영구','영구',6,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_RETENTION_PERIOD' AND CODE_VALUE='PERM');

-- CD_PCI_CATEGORY (신용정보법 시행령 분류)
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_PCI_CATEGORY','IDENT','식별정보','식별정보 (신용정보법 시행령 분류)',1,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_PCI_CATEGORY' AND CODE_VALUE='IDENT');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_PCI_CATEGORY','TRX','신용거래','신용거래 (신용정보법 시행령 분류)',2,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_PCI_CATEGORY' AND CODE_VALUE='TRX');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_PCI_CATEGORY','SCORE','신용도','신용도 (신용정보법 시행령 분류)',3,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_PCI_CATEGORY' AND CODE_VALUE='SCORE');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_PCI_CATEGORY','ABILITY','신용능력','신용능력 (신용정보법 시행령 분류)',4,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_PCI_CATEGORY' AND CODE_VALUE='ABILITY');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_PCI_CATEGORY','PUBLIC','공공정보','공공정보 (신용정보법 시행령 분류)',5,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_PCI_CATEGORY' AND CODE_VALUE='PUBLIC');

-- CD_ISOLATION_LEVEL
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_ISOLATION_LEVEL','L1','운영망','운영망',1,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_ISOLATION_LEVEL' AND CODE_VALUE='L1');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_ISOLATION_LEVEL','L2','준격리','준격리',2,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_ISOLATION_LEVEL' AND CODE_VALUE='L2');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_ISOLATION_LEVEL','L3','완전격리','완전격리',3,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_ISOLATION_LEVEL' AND CODE_VALUE='L3');

-- CD_STATUS
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_STATUS','PLANNED','계획','계획',1,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_STATUS' AND CODE_VALUE='PLANNED');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_STATUS','ACTIVE','운영중','운영중',2,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_STATUS' AND CODE_VALUE='ACTIVE');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_STATUS','DEPRECATED','폐기예정','폐기예정',3,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_STATUS' AND CODE_VALUE='DEPRECATED');

-- CD_TABLE_TYPE
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_TABLE_TYPE','BASE','테이블','테이블',1,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_TABLE_TYPE' AND CODE_VALUE='BASE');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_TABLE_TYPE','VIEW','뷰','뷰',2,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_TABLE_TYPE' AND CODE_VALUE='VIEW');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_TABLE_TYPE','MVIEW','MView','MView',3,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_TABLE_TYPE' AND CODE_VALUE='MVIEW');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_TABLE_TYPE','EXT','외부','외부',4,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_TABLE_TYPE' AND CODE_VALUE='EXT');

-- CD_INDEX_TYPE
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_INDEX_TYPE','NORMAL','NORMAL','일반 인덱스',1,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_INDEX_TYPE' AND CODE_VALUE='NORMAL');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_INDEX_TYPE','UNIQUE','UNIQUE','고유 인덱스',2,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_INDEX_TYPE' AND CODE_VALUE='UNIQUE');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_INDEX_TYPE','BITMAP','BITMAP','비트맵 인덱스',3,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_INDEX_TYPE' AND CODE_VALUE='BITMAP');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_INDEX_TYPE','FUNCTION','FUNCTION','함수기반 인덱스',4,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_INDEX_TYPE' AND CODE_VALUE='FUNCTION');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_INDEX_TYPE','REVERSE','REVERSE','리버스키 인덱스',5,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_INDEX_TYPE' AND CODE_VALUE='REVERSE');

-- CD_INDEX_PURPOSE
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_INDEX_PURPOSE','PK','PK','기본키',1,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_INDEX_PURPOSE' AND CODE_VALUE='PK');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_INDEX_PURPOSE','FK','FK','외래키',2,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_INDEX_PURPOSE' AND CODE_VALUE='FK');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_INDEX_PURPOSE','SEARCH','SEARCH','조회',3,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_INDEX_PURPOSE' AND CODE_VALUE='SEARCH');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_INDEX_PURPOSE','JOIN','JOIN','조인',4,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_INDEX_PURPOSE' AND CODE_VALUE='JOIN');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_INDEX_PURPOSE','TUNING','TUNING','튜닝',5,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_INDEX_PURPOSE' AND CODE_VALUE='TUNING');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_INDEX_PURPOSE','SORT','SORT','정렬',6,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_INDEX_PURPOSE' AND CODE_VALUE='SORT');

-- CD_SEQUENCE_PURPOSE
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_SEQUENCE_PURPOSE','PK','PK','기본키 채번',1,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_SEQUENCE_PURPOSE' AND CODE_VALUE='PK');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_SEQUENCE_PURPOSE','BIZ_KEY','BIZ_KEY','업무키 채번',2,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_SEQUENCE_PURPOSE' AND CODE_VALUE='BIZ_KEY');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_SEQUENCE_PURPOSE','TEMP','TEMP','임시 채번',3,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_SEQUENCE_PURPOSE' AND CODE_VALUE='TEMP');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_SEQUENCE_PURPOSE','ETC','ETC','기타',4,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_SEQUENCE_PURPOSE' AND CODE_VALUE='ETC');

-- CD_MASKING_RULE
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_MASKING_RULE','NAME','이름','이름',1,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_MASKING_RULE' AND CODE_VALUE='NAME');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_MASKING_RULE','RRN','주민번호','주민번호',2,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_MASKING_RULE' AND CODE_VALUE='RRN');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_MASKING_RULE','PHONE','전화번호','전화번호',3,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_MASKING_RULE' AND CODE_VALUE='PHONE');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_MASKING_RULE','CARD','카드번호','카드번호',4,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_MASKING_RULE' AND CODE_VALUE='CARD');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_MASKING_RULE','EMAIL','이메일','이메일',5,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_MASKING_RULE' AND CODE_VALUE='EMAIL');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_MASKING_RULE','ADDR','주소','주소',6,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_MASKING_RULE' AND CODE_VALUE='ADDR');
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_MASKING_RULE','FULL','전체마스킹','전체마스킹',7,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_MASKING_RULE' AND CODE_VALUE='FULL');

-- CD_SERVICE: §7.1 호환을 위한 UNASSIGNED 더미 1건만 적재
INSERT INTO TB_META_CODE(CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT 'CD_SERVICE','UNASSIGNED','미지정','초기 적재용 미지정 서비스(담당자 매핑 후 교체)',1,'INITIAL_LOAD','INITIAL_LOAD' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_META_CODE WHERE CODE_GROUP='CD_SERVICE' AND CODE_VALUE='UNASSIGNED');

-- TB_META_CODE_HIST 동시 적재: ('I','INITIAL_LOAD') 미존재 행만
INSERT INTO TB_META_CODE_HIST (
    HIST_ID, HIST_TYPE, HIST_AT, HIST_BY, CHANGE_REASON,
    CODE_GROUP, CODE_VALUE, CODE_NAME, DESCRIPTION,
    SORT_ORDER, USE_YN,
    CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
)
SELECT
    SEQ_META_HIST_ID.NEXTVAL, 'I', SYSTIMESTAMP, USER, 'INITIAL_LOAD',
    c.CODE_GROUP, c.CODE_VALUE, c.CODE_NAME, c.DESCRIPTION,
    c.SORT_ORDER, c.USE_YN,
    c.CREATED_BY, c.CREATED_AT, c.UPDATED_BY, c.UPDATED_AT
FROM TB_META_CODE c
WHERE NOT EXISTS (
    SELECT 1 FROM TB_META_CODE_HIST h
     WHERE h.CODE_GROUP    = c.CODE_GROUP
       AND h.CODE_VALUE    = c.CODE_VALUE
       AND h.HIST_TYPE     = 'I'
       AND h.CHANGE_REASON = 'INITIAL_LOAD'
)
;

COMMIT;
