-- =====================================================================
-- 03_initial_load.sql — 시스템 카탈로그 → 메타 테이블 적재 + HIST
-- 실행 순서: 3 / 3
-- 선행: 02_common_code.sql
-- 후행: (없음 — 이후 비즈니스 메타 수기 UPDATE)
-- 출처: DB_메타정보_관리체계_표준설계.md §7 (7.1~7.5)
-- 사전 수정 필요: WHERE OWNER IN ('SVC1','SVC2', ...) 의 스키마 목록을
--               실제 대상 스키마로 교체한 뒤 실행
-- 구성: 7.x 본 적재 → 7.5.x HIST 적재 를 테이블 단위로 번갈아 실행하여
--       동일 트랜잭션으로 묶고, 마지막에 일괄 COMMIT.
-- HIST 고정값: HIST_TYPE='I', HIST_BY=USER, CHANGE_REASON='INITIAL_LOAD'
-- =====================================================================

-- =====================================================================
-- §7.1 TB_META_TABLE — 테이블 적재
-- =====================================================================
INSERT INTO TB_META_TABLE (
    TABLE_ID, SCHEMA_NAME, TABLE_NAME, LOGICAL_NAME, DESCRIPTION,
    TABLE_TYPE_CD, SERVICE_CD, OWNER_EMP_ID,
    KEY_TABLE_YN, ISOLATION_YN, PII_YN, PCI_YN,
    RETENTION_PERIOD_CD, STATUS_CD,
    CREATED_BY, UPDATED_BY
)
SELECT
    SEQ_META_TABLE_ID.NEXTVAL,
    t.OWNER,
    t.TABLE_NAME,
    NULL,                                 -- LOGICAL_NAME: 이후 담당자 입력
    c.COMMENTS,                           -- ALL_TAB_COMMENTS
    'BASE',
    'UNASSIGNED',                         -- 이후 매핑
    'SYSTEM',                             -- 담당자 미지정
    'N','N','N','N',
    'Y5',                                 -- 안전 기본값: 5년 (추후 재분류)
    'ACTIVE',
    USER, USER
FROM ALL_TABLES t
LEFT JOIN ALL_TAB_COMMENTS c
       ON c.OWNER = t.OWNER AND c.TABLE_NAME = t.TABLE_NAME
WHERE t.OWNER IN ('SVC1','SVC2'/* 대상 스키마 목록 */)
  AND t.TABLE_NAME NOT LIKE 'BIN$%'       -- recycle bin 제외
  AND t.TABLE_NAME NOT LIKE 'TB_META_%'   -- 자기 자신 제외
;

-- §7.5.1 TB_META_TABLE_HIST — 방금 적재한 TB_META_TABLE 전체를 HIST 스냅샷
INSERT INTO TB_META_TABLE_HIST (
    HIST_ID, HIST_TYPE, HIST_AT, HIST_BY, CHANGE_REASON,
    TABLE_ID, SCHEMA_NAME, TABLE_NAME, LOGICAL_NAME, DESCRIPTION,
    TABLE_TYPE_CD, SERVICE_CD, OWNER_EMP_ID, SECONDARY_EMP_ID,
    KEY_TABLE_YN, ISOLATION_YN, ISOLATION_LEVEL_CD,
    PII_YN, PCI_YN, RETENTION_PERIOD_CD, RETENTION_BASIS, TOS_CD,
    STATUS_CD, REMARK,
    CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
)
SELECT
    SEQ_META_HIST_ID.NEXTVAL, 'I', SYSTIMESTAMP, USER, 'INITIAL_LOAD',
    TABLE_ID, SCHEMA_NAME, TABLE_NAME, LOGICAL_NAME, DESCRIPTION,
    TABLE_TYPE_CD, SERVICE_CD, OWNER_EMP_ID, SECONDARY_EMP_ID,
    KEY_TABLE_YN, ISOLATION_YN, ISOLATION_LEVEL_CD,
    PII_YN, PCI_YN, RETENTION_PERIOD_CD, RETENTION_BASIS, TOS_CD,
    STATUS_CD, REMARK,
    CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
FROM TB_META_TABLE
;

-- =====================================================================
-- §7.2 TB_META_COLUMN — 컬럼 적재
-- =====================================================================
INSERT INTO TB_META_COLUMN (
    COLUMN_ID, TABLE_ID, COLUMN_NAME, COLUMN_ORDER,
    LOGICAL_NAME, DESCRIPTION,
    DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE,
    NULLABLE_YN, DEFAULT_VALUE,
    PK_YN, UK_YN, FK_YN,
    PII_YN, PCI_YN, SENSITIVITY_CD,
    ENCRYPTION_YN, MASKING_YN,
    STATUS_CD, CREATED_BY, UPDATED_BY
)
SELECT
    SEQ_META_COLUMN_ID.NEXTVAL,
    mt.TABLE_ID,
    tc.COLUMN_NAME,
    tc.COLUMN_ID,
    NULL,
    cc.COMMENTS,
    tc.DATA_TYPE, tc.DATA_LENGTH, tc.DATA_PRECISION, tc.DATA_SCALE,
    CASE tc.NULLABLE WHEN 'Y' THEN 'Y' ELSE 'N' END,
    SUBSTR(tc.DATA_DEFAULT, 1, 500),
    NVL2(pk.COLUMN_NAME,'Y','N'),
    NVL2(uk.COLUMN_NAME,'Y','N'),
    NVL2(fk.COLUMN_NAME,'Y','N'),
    'N','N','LOW',
    'N','N',
    'ACTIVE', USER, USER
FROM ALL_TAB_COLUMNS tc
JOIN TB_META_TABLE mt
      ON mt.SCHEMA_NAME = tc.OWNER AND mt.TABLE_NAME = tc.TABLE_NAME
LEFT JOIN ALL_COL_COMMENTS cc
      ON cc.OWNER = tc.OWNER AND cc.TABLE_NAME = tc.TABLE_NAME AND cc.COLUMN_NAME = tc.COLUMN_NAME
LEFT JOIN (
    SELECT acc.OWNER, acc.TABLE_NAME, acc.COLUMN_NAME
      FROM ALL_CONSTRAINTS ac
      JOIN ALL_CONS_COLUMNS acc
        ON ac.OWNER = acc.OWNER AND ac.CONSTRAINT_NAME = acc.CONSTRAINT_NAME
     WHERE ac.CONSTRAINT_TYPE = 'P'
) pk ON pk.OWNER = tc.OWNER AND pk.TABLE_NAME = tc.TABLE_NAME AND pk.COLUMN_NAME = tc.COLUMN_NAME
LEFT JOIN (
    SELECT acc.OWNER, acc.TABLE_NAME, acc.COLUMN_NAME
      FROM ALL_CONSTRAINTS ac
      JOIN ALL_CONS_COLUMNS acc
        ON ac.OWNER = acc.OWNER AND ac.CONSTRAINT_NAME = acc.CONSTRAINT_NAME
     WHERE ac.CONSTRAINT_TYPE = 'U'
) uk ON uk.OWNER = tc.OWNER AND uk.TABLE_NAME = tc.TABLE_NAME AND uk.COLUMN_NAME = tc.COLUMN_NAME
LEFT JOIN (
    SELECT acc.OWNER, acc.TABLE_NAME, acc.COLUMN_NAME
      FROM ALL_CONSTRAINTS ac
      JOIN ALL_CONS_COLUMNS acc
        ON ac.OWNER = acc.OWNER AND ac.CONSTRAINT_NAME = acc.CONSTRAINT_NAME
     WHERE ac.CONSTRAINT_TYPE = 'R'
) fk ON fk.OWNER = tc.OWNER AND fk.TABLE_NAME = tc.TABLE_NAME AND fk.COLUMN_NAME = tc.COLUMN_NAME
;

-- §7.5.2 TB_META_COLUMN_HIST
INSERT INTO TB_META_COLUMN_HIST (
    HIST_ID, HIST_TYPE, HIST_AT, HIST_BY, CHANGE_REASON,
    COLUMN_ID, TABLE_ID, COLUMN_NAME, COLUMN_ORDER,
    LOGICAL_NAME, DESCRIPTION,
    DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE,
    NULLABLE_YN, DEFAULT_VALUE,
    PK_YN, UK_YN, FK_YN,
    PII_YN, PCI_YN, PCI_CATEGORY_CD, SENSITIVITY_CD,
    ENCRYPTION_YN, ENCRYPTION_ALG, MASKING_YN, MASKING_RULE_CD,
    RETENTION_PERIOD_CD, TOS_CD, STATUS_CD, REMARK,
    CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
)
SELECT
    SEQ_META_HIST_ID.NEXTVAL, 'I', SYSTIMESTAMP, USER, 'INITIAL_LOAD',
    COLUMN_ID, TABLE_ID, COLUMN_NAME, COLUMN_ORDER,
    LOGICAL_NAME, DESCRIPTION,
    DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE,
    NULLABLE_YN, DEFAULT_VALUE,
    PK_YN, UK_YN, FK_YN,
    PII_YN, PCI_YN, PCI_CATEGORY_CD, SENSITIVITY_CD,
    ENCRYPTION_YN, ENCRYPTION_ALG, MASKING_YN, MASKING_RULE_CD,
    RETENTION_PERIOD_CD, TOS_CD, STATUS_CD, REMARK,
    CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
FROM TB_META_COLUMN
;

-- =====================================================================
-- §7.3 인덱스 적재
-- =====================================================================

-- §7.3.1 TB_META_INDEX — 헤더
INSERT INTO TB_META_INDEX (
    INDEX_ID, TABLE_ID, INDEX_NAME, INDEX_TYPE_CD,
    TABLESPACE_NAME, PURPOSE_CD, STATUS_CD,
    CREATED_BY, UPDATED_BY
)
SELECT
    SEQ_META_INDEX_ID.NEXTVAL,
    mt.TABLE_ID,
    i.INDEX_NAME,
    CASE
      WHEN i.UNIQUENESS = 'UNIQUE' THEN 'UNIQUE'
      WHEN i.INDEX_TYPE = 'BITMAP' THEN 'BITMAP'
      WHEN i.INDEX_TYPE LIKE 'FUNCTION%' THEN 'FUNCTION'
      ELSE 'NORMAL'
    END,
    i.TABLESPACE_NAME,
    CASE WHEN i.UNIQUENESS = 'UNIQUE' THEN 'PK' ELSE 'SEARCH' END,  -- 초기 추정값
    'ACTIVE', USER, USER
FROM ALL_INDEXES i
JOIN TB_META_TABLE mt
      ON mt.SCHEMA_NAME = i.TABLE_OWNER AND mt.TABLE_NAME = i.TABLE_NAME
WHERE i.TABLE_OWNER IN ('SVC1','SVC2'/* 대상 스키마 목록 */)
;

-- §7.5.3 TB_META_INDEX_HIST
INSERT INTO TB_META_INDEX_HIST (
    HIST_ID, HIST_TYPE, HIST_AT, HIST_BY, CHANGE_REASON,
    INDEX_ID, TABLE_ID, INDEX_NAME, INDEX_TYPE_CD,
    TABLESPACE_NAME, INITRANS, PCTFREE,
    PURPOSE_CD, PERFORMANCE_NOTE, CREATE_DDL,
    STATUS_CD,
    CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
)
SELECT
    SEQ_META_HIST_ID.NEXTVAL, 'I', SYSTIMESTAMP, USER, 'INITIAL_LOAD',
    INDEX_ID, TABLE_ID, INDEX_NAME, INDEX_TYPE_CD,
    TABLESPACE_NAME, INITRANS, PCTFREE,
    PURPOSE_CD, PERFORMANCE_NOTE, CREATE_DDL,
    STATUS_CD,
    CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
FROM TB_META_INDEX
;

-- §7.3.2 TB_META_INDEX_COLUMN — 컬럼
INSERT INTO TB_META_INDEX_COLUMN (INDEX_ID, COLUMN_POS, COLUMN_NAME, SORT_ORDER)
SELECT mi.INDEX_ID, ic.COLUMN_POSITION, ic.COLUMN_NAME, ic.DESCEND
FROM ALL_IND_COLUMNS ic
JOIN TB_META_TABLE mt
  ON mt.SCHEMA_NAME = ic.TABLE_OWNER AND mt.TABLE_NAME = ic.TABLE_NAME
JOIN TB_META_INDEX mi
  ON mi.TABLE_ID = mt.TABLE_ID AND mi.INDEX_NAME = ic.INDEX_NAME
WHERE ic.TABLE_OWNER IN ('SVC1','SVC2'/* 대상 스키마 목록 */)
;

-- §7.5.4 TB_META_INDEX_COLUMN_HIST
INSERT INTO TB_META_INDEX_COLUMN_HIST (
    HIST_ID, HIST_TYPE, HIST_AT, HIST_BY, CHANGE_REASON,
    INDEX_ID, COLUMN_POS, COLUMN_NAME, SORT_ORDER, FUNC_EXPRESSION
)
SELECT
    SEQ_META_HIST_ID.NEXTVAL, 'I', SYSTIMESTAMP, USER, 'INITIAL_LOAD',
    INDEX_ID, COLUMN_POS, COLUMN_NAME, SORT_ORDER, FUNC_EXPRESSION
FROM TB_META_INDEX_COLUMN
;

-- =====================================================================
-- §7.4 TB_META_SEQUENCE — 시퀀스 적재
-- =====================================================================
INSERT INTO TB_META_SEQUENCE (
    SEQUENCE_ID, SCHEMA_NAME, SEQUENCE_NAME,
    MIN_VALUE, MAX_VALUE, INCREMENT_BY, CACHE_SIZE,
    CYCLE_YN, ORDER_YN, PURPOSE_CD, STATUS_CD,
    CREATED_BY, UPDATED_BY
)
SELECT
    SEQ_META_SEQUENCE_ID.NEXTVAL,
    SEQUENCE_OWNER, SEQUENCE_NAME,
    MIN_VALUE, MAX_VALUE, INCREMENT_BY, CACHE_SIZE,
    CASE CYCLE_FLAG WHEN 'Y' THEN 'Y' ELSE 'N' END,
    CASE ORDER_FLAG WHEN 'Y' THEN 'Y' ELSE 'N' END,
    'ETC',                    -- 용도는 담당자 업데이트
    'ACTIVE', USER, USER
FROM ALL_SEQUENCES
WHERE SEQUENCE_OWNER IN ('SVC1','SVC2'/* 대상 스키마 목록 */)
;

-- §7.5.5 TB_META_SEQUENCE_HIST
INSERT INTO TB_META_SEQUENCE_HIST (
    HIST_ID, HIST_TYPE, HIST_AT, HIST_BY, CHANGE_REASON,
    SEQUENCE_ID, SCHEMA_NAME, SEQUENCE_NAME,
    MIN_VALUE, MAX_VALUE, INCREMENT_BY, START_WITH, CACHE_SIZE,
    CYCLE_YN, ORDER_YN, PURPOSE_CD,
    USED_FOR_TABLE, USED_FOR_COLUMN, CREATE_DDL, STATUS_CD,
    CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
)
SELECT
    SEQ_META_HIST_ID.NEXTVAL, 'I', SYSTIMESTAMP, USER, 'INITIAL_LOAD',
    SEQUENCE_ID, SCHEMA_NAME, SEQUENCE_NAME,
    MIN_VALUE, MAX_VALUE, INCREMENT_BY, START_WITH, CACHE_SIZE,
    CYCLE_YN, ORDER_YN, PURPOSE_CD,
    USED_FOR_TABLE, USED_FOR_COLUMN, CREATE_DDL, STATUS_CD,
    CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
FROM TB_META_SEQUENCE
;

COMMIT;
